Using fabs() function instead abs()
php-geospatial/geospatial pull request #24
Opened 2018-03-10 14:39 UTC by xoptov

This fix resolving compilation warning when making so.

2018-03-12 10:31 UTC, derickr requested changes

2018-03-12 10:31 UTC, derickr commented on geospatial.c
> +	while (fabs(phi - phiP) > precision) {
This PR made one of the tests fail: https://travis-ci.org/php-geospatial/geospatial/jobs/351708921#L643

Can you investigate whether the new value is correct, as the loop where you changed ``abs`` to ``fabs`` might now run once more or less?

2018-03-16 20:03 UTC, xoptov commented on geospatial.c
> +	while (fabs(phi - phiP) > precision) {
I have warning when compile geospatil.so in FreeBSD 10.3. Warning saying about using fabs instead abs. When I changed abs to fabs warning is gone!

2018-04-03 09:06 UTC, derickr commented on geospatial.c
> +	while (fabs(phi - phiP) > precision) {
That's fine, but it breaks a test if you change it. So either the test is wrong, or something else is going on.

2025-07-01 11:10 UTC, closed without merging